### ISSUE TITLE
Request: accept GHO-formatted links

### ISSUE THREAD

**Issue by herrchin** [TheCre8r/WME-PL-Jump-Release#3]
(aka strip the google.com leading and trailing junk, handle character codes for punctuation if need be)

**Comment by TheCre8r** [comment]
Sorry for the delay, will you please provide me with an example?

**Comment by herrchin** [comment]
This is a PL as copied from a GHO using a Copy Link Address: `https://www.google.com/url?q=https%3A%2F%2Fwww.waze.com%2Fen-US%2Feditor%2F%3Fenv%3Dusa%26lon%3D-111.97737%26lat%3D40.53859%26zoom%3D5%26segments%3D61419348%2C63725922%2C68716172%2C63725923&sa=D&sntz=1&usg=AFQjCNFm8XWa7Wklxz074GdLJBf_4UU9Lw`

After giving it a urlclean.com pass, it looks like `https://www.google.com/url?q=https://www.waze.com/en-US/editor/?env=usa&lon=-111.97737&lat=40.53859&zoom=5&segments=61419348,63725922,68716172,63725923`

But as you can see, even then the leading google.com redirect still needs to be stripped to be a "native" URL.

**Comment by TheCre8r** [comment]
Added support in Version 0.0.12.8
