### ISSUE TITLE
No longer showing in Beta

### ISSUE THREAD

**Issue by jm6087** [TheCre8r/WME-PL-Jump-Release#4]
With the updated Beta release today, PL Jump does not appear to be showing up in my WME anymore.  It still shows up in Production.

**Comment by TheCre8r** [comment]
Thank you!
The message in console is as follows:
ERROR: Execution of script 'WME PL Jump' failed! WME Hack: can't detect WME main JS

This appears to be an issue with the requirement WazeWrap. Issue has been sent to those developers,

**Comment by TheCre8r** [comment]
Corrected Issue. Version 0.0.12.7 solves issue. Thanks again!
